### ISSUE TITLE
path should be a `path.relative()`d string, but got "./@types/index.d.ts"

### ISSUE THREAD

**Issue by Can2Nya** [wclr/yalc#109]
``` 
yalc version: 1.0.0-pre.34
yarn version: 1.21.1
npm 6.4.1
node v10.13.0 
```

This is my project directory：

```
├── @types
│   └── index.d.ts
├── CHANGELOG.md
├── README.md
├── package-lock.json
├── package.json
├── src
│   ........
├── tsconfig.json
├── watch.js
└── yarn.lock
```

When I execute the command `yalc publish`，I got those error:

```
(node:55687) UnhandledPromiseRejectionWarning: RangeError: path should be a `path.relative()`d string, but got "./@types/index.d.ts"
    at throwError (/Users/heier/.config/yarn/global/node_modules/yalc/node_modules/ignore/index.js:337:9)
    at checkPath (/Users/heier/.config/yarn/global/node_modules/yalc/node_modules/ignore/index.js:356:12)
    at Ignore._test (/Users/heier/.config/yarn/global/node_modules/yalc/node_modules/ignore/index.js:473:5)
    at Ignore.ignores (/Users/heier/.config/yarn/global/node_modules/yalc/node_modules/ignore/index.js:512:17)
    at /Users/heier/.config/yarn/global/node_modules/yalc/src/copy.js:101:80
    at Array.filter (<anonymous>)
    at Object.<anonymous> (/Users/heier/.config/yarn/global/node_modules/yalc/src/copy.js:101:39)
    at step (/Users/heier/.config/yarn/global/node_modules/yalc/src/copy.js:43:23)
    at Object.next (/Users/heier/.config/yarn/global/node_modules/yalc/src/copy.js:24:53)
    at fulfilled (/Users/heier/.config/yarn/global/node_modules/yalc/src/copy.js:15:58)
(node:55687) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:55687) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

No issues with  `yalc@1.0.0-pre.23`

**Comment by whitecolor** [comment]
What your `.npmignore` looks like?

**Comment by whitecolor** [comment]
Seems the error in `ignore` module, it is used only to parse `.yalcignore`. Do you have `.yalcignore` file?

**Comment by Can2Nya** [comment]
> Seems the error in `ignore` module, it is used only to parse and handle `.yalcignore`. Do you have `.yalcignore` file?

I don‘t have any `.yalcignore` file, need to add it?

**Comment by whitecolor** [comment]
> I don‘t have any .yalcignore file, need to add it?

No. Not sure then why you have this error.

**Comment by Can2Nya** [comment]
> > I don‘t have any .yalcignore file, need to add it?
> 
> No. Not sure then why you have this error.

when I delete the folder `@type`, It works fine.
I can't understand why `./@types/index.d.ts` it not `path.relative()` string.

**Comment by euphocat** [comment]
got the same issue here, but I need my `@types` !

**Comment by whitecolor** [comment]
I don't understand the setup that causes the issue.

**Comment by euphocat** [comment]
after I searched a bit mode, I think it's easy to reproduce. I have a typescript project and a `@types` folder containing a `index.d.ts`. For a reason I can't find yet, `npm-packlist` output `./@types/index.d.ts` which is not valid according to the function check: `checkPath.isNotRelative(path)`

**Comment by msudgh** [comment]
I have the same issue and tried to put the project's `@types` directory inside `.npmignore` which was helpful.

**Comment by wclr** [comment]
Please, make the repo where I can reproduce the error.

**Comment by elchininet** [comment]
Hi @wclr,
You can test [in one of my repos](https://github.com/elchininet/postcss-rtlcss). The `dist` folder contains a `dist/@types/index.d.ts` file and it is impossible to run `yalc publish` if it is not removed:

```bash
yalc publish

Publish package in yalc local repo

Opciones:
  --version            Muestra número de versión                      [booleano]
  --help               Muestra ayuda                                  [booleano]
  --sig                                               [booleano] [defecto: true]
  --dev-mod                                           [booleano] [defecto: true]
  --workspace-resolve                                            [defecto: true]

RangeError: path should be a `path.relative()`d string, but got "./@types/index.d.ts"
    at throwError (/Users/elchininet/.nvm/versions/node/v12.0.0/lib/node_modules/yalc/node_modules/ignore/index.js:366:9)
    at checkPath (/Users/elchininet/.nvm/versions/node/v12.0.0/lib/node_modules/yalc/node_modules/ignore/index.js:385:12)
    at Ignore._test (/Users/elchininet/.nvm/versions/node/v12.0.0/lib/node_modules/yalc/node_modules/ignore/index.js:502:5)
    at Ignore.ignores (/Users/elchininet/.nvm/versions/node/v12.0.0/lib/node_modules/yalc/node_modules/ignore/index.js:541:17)
    at /Users/elchininet/.nvm/versions/node/v12.0.0/lib/node_modules/yalc/src/copy.js:152:80
    at Array.filter (<anonymous>)
    at /Users/elchininet/.nvm/versions/node/v12.0.0/lib/node_modules/yalc/src/copy.js:152:39
    at step (/Users/elchininet/.nvm/versions/node/v12.0.0/lib/node_modules/yalc/src/copy.js:44:23)
    at Object.next (/Users/elchininet/.nvm/versions/node/v12.0.0/lib/node_modules/yalc/src/copy.js:25:53)
    at fulfilled (/Users/elchininet/.nvm/versions/node/v12.0.0/lib/node_modules/yalc/src/copy.js:16:58)
```

**Comment by wclr** [comment]
Should be fixed in the latest published.

**Comment by elchininet** [comment]
Hi @wclr,
FYI, I upgraded `yalc` to `yalc@1.0.0-pre.50` and the issue is still occurring.

**Comment by wclr** [comment]
the latest should be pre.52

**Comment by elchininet** [comment]
Yes, it is solved in `yalc@1.0.0-pre.53`.
